name: MacOS (amd64)

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: macos-latest

    steps:
      - name: Download from moonbitlang.com
        run: |
          mkdir -p $GITHUB_WORKSPACE/download
          cd $GITHUB_WORKSPACE/download
          rm -rf .* * || true
          wget https://cli.moonbitlang.com/macos_intel/moon \
            https://cli.moonbitlang.com/macos_intel/moonc \
            https://cli.moonbitlang.com/macos_intel/moonfmt \
            https://cli.moonbitlang.com/macos_intel/moonrun \
            https://cli.moonbitlang.com/macos_intel/moondoc \
            https://cli.moonbitlang.com/macos_intel/mooninfo \
            https://cli.moonbitlang.com/macos_intel/moon_cove_report
          ls -alth
          file moon
          chmod +x ./moon && ./moon version
          chmod +x ./moonc && ./moonc -v
