name: Ubuntu

on:
  workflow_dispatch:

jobs:
  tracker-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: prj

      - name: Build npm project
        working-directory: ./prj
        run: |
          npm ci
          npm run build
      
      - name: Run npm project
        working-directory: ./prj
        env:
          MULTIMOON_ARCH: ubuntu_amd64
        run: |
          node dist/index.js
