name: Windows (x64)

on:
  workflow_dispatch:

jobs:
  tracker-main:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: prj

      - name: Build npm project
        working-directory: ./prj
        run: |
          npm ci
          npm run build
      
      - name: Run npm project
        working-directory: ./prj
        env:
          MULTIMOON_ARCH: windows_x64
        run: |
          node dist/index.js
